name: Flask CI Pipeline

on:
  push:
    branches:
      # - main
      - staging
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      STAGING: ${{ secrets.STAGING_HOST }}
      PROD: ${{ secrets.PRODUCTION_HOST }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          pip install pytest
          pytest
      
      - name: Configuring ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $STAGING >> ~/.ssh/known_hosts
          ssh-keyscan -H $PROD >> ~/.ssh/known_hosts

      - name: Deploy to Staging environment
        run: |
          ssh ubuntu@$STAGING << EOF
            set -e
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            cd /home/ubuntu
            if [ ! -d "app/.git" ]; then
              rm -rf app
              git clone git@github.com:tanneerugowtham6/GitHub_Actions_CI_CD_Assignment.git app
            fi
            cd app
            # git pull origin staging
            git fetch origin
            git reset --hard origin/staging
            /home/ubuntu/venv/bin/pip install -r requirements.txt
            sudo systemctl restart flask-app
          EOF
